language: ruby
os:
  - linux
rvm:
  - 3.0
  - 3.1
  - ruby-head
branches:
  except:
    - "readme-edits"
before_install:
  - gem update --system

matrix:
  allow_failures:
    - rvm: ruby-head
    
script: 
  - bundle exec rake spec